# Generated by Django 3.1.2 on 2020-11-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(help_text='title of message.', max_length=120)),
                ('Asal', models.TextField(help_text="what's on your mind ...")),
                ('pesan', models.CharField(default='APA AJA', max_length=1000)),
            ],
        ),
    ]
